<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ3tlkmq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ3tlkmq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJ3tlkmq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJ3tlkmq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJ3tlkmq\appProdProjectContainer([
    'container.build_hash' => 'J3tlkmq',
    'container.build_id' => '667a0b33',
    'container.build_time' => 1626039109,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ3tlkmq');
